name: Generate and Deploy

on:
  push:
    branches: [main]
    paths-ignore:  # 忽略index.html避免无限循环
      - 'index.html'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:  # 关键：添加写入权限
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Generate HTML
      run: |
        python html.py
        cat index.html  # 显示生成的文件内容
    
    - name: Commit and push changes
      run: |
        # 配置Git用户
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # 添加更改
        git add index.html
        
        # 检查是否有更改
        if git diff-index --quiet HEAD --; then
          echo "没有更改需要提交"
        else
          # 提交更改
          git commit -m "自动更新图片列表"
          
          # 使用特殊URL格式推送
          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" HEAD:main
        fi
